name: Terraform Manual Deploy

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform 

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Auth to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Terraform Init
        run: terraform init 

      - name: Terraform Plan
        run: terraform plan -lock=false
        env:
          TF_VAR_api_key_odds: ${{ secrets.API_KEY_ODDS }}
          TF_VAR_api_key_sd:   ${{ secrets.API_KEY_SD }}
          TF_VAR_gemini_key:   ${{ secrets.GEMINI_KEY }}

      - name: Terraform Apply
        run: terraform apply -auto-approve -lock=false
        env:
          TF_VAR_api_key_odds: ${{ secrets.API_KEY_ODDS }}
          TF_VAR_api_key_sd:   ${{ secrets.API_KEY_SD }}
          TF_VAR_gemini_key:   ${{ secrets.GEMINI_KEY }}
